image: registry.gitlab.com/orobardet/gitlab-ci-linter/build

stages:
  - vendors
  - checks
  - tests
  - build
  - packaging
  - releasenote

variables:
  AF_BINARY_URL: "https://api.bintray.com/content/orobardet/gitlab-ci-linter/gitlab-ci-linter"
  AF_BINARY_SUBJECT: "orobardet"
  AF_BINARY_REPO: "gitlab-ci-linter"
  AF_BINARY_PACKAGE: "gitlab-ci-linter"
  CI_GITLAB_URL: "https://gitlab.com"
  DEBEMAIL: $GITLAB_USER_EMAIL
  DEBFULLNAME: $GITLAB_USER_NAME

before_script:
  - ln -s $CI_PROJECT_DIR $GOPATH/src/
  - cd $GOPATH/src/$(basename $CI_PROJECT_DIR)

get vendors:
  stage: vendors
  script:
    - dep ensure
  artifacts:
    name: "${CI_JOB_NAME}_${CI_COMMIT_REF_NAME}"
    paths:
      - vendor/
    expire_in: 1 hour

gofmt:
  stage: checks
  script: gofmt -s -l -e $(find . -name "*.go" -type f -not -path "./vendor/*")

govet:
  stage: checks
  script: go vet

go test:
  stage: tests
  script: go test

.build_binary: &_binary
  stage: build
  dependencies:
    - get vendors
  script:
    - export GOTARGET=${CI_JOB_NAME##* }
    - export GOOS=${GOTARGET%%-*}
    - export GOARCH=${GOTARGET##*-}
    - export EXT="$([[ "$GOOS" = "windows" ]] && echo ".exe")"
    - export BINARY=gitlab-ci-linter.${GOOS}-${GOARCH}${EXT}
    - if [[ $VERSION ]] ; then export VERSION=${VERSION##v} ; fi
    - make

.build_binary_dev: &_binary_dev
  <<: *_binary
  variables:
    DEBUG: "1"
  only:
   - branches
  artifacts:
    name: "${CI_JOB_NAME}"
    paths:
      - gitlab-ci-linter.*
    expire_in: 1 week

.build_binary_release: &_binary_release
  <<: *_binary
  variables:
    VERSION: ${CI_COMMIT_TAG}
    RELEASE: "1"
  only:
   - tags
  after_script:
    - curl -T $BINARY -u${AFI_API_USER}:${AF_API_KEY} "$AF_BINARY_URL/content/$AF_BINARY_SUBJECT/$AF_BINARY_REPO/$AF_BINARY_PACKAGE/${VERSION}/$(basename $BINARY)?override=1&publish=1"
  artifacts:
    name: "${CI_JOB_NAME}"
    paths:
      - gitlab-ci-linter.*
    expire_in: 1 year

dev build linux-386: *_binary_dev
dev build linux-amd64: *_binary_dev
dev build linux-arm: *_binary_dev
dev build linux-arm64: *_binary_dev
dev build windows-386: *_binary_dev
dev build windows-amd64: *_binary_dev
dev build darwin-386: *_binary_dev
dev build darwin-amd64: *_binary_dev

release build linux-386: *_binary_release
release build linux-amd64: *_binary_release
release build linux-arm: *_binary_release
release build linux-arm64: *_binary_release
release build windows-386: *_binary_release
release build windows-amd64: *_binary_release
release build darwin-386: *_binary_release
release build darwin-amd64: *_binary_release

.build_debian: &_build_debian
  stage: packaging
  script:
    - export GOTARGET=${CI_JOB_NAME##* }
    - export GOOS=${GOTARGET%%-*}
    - export ARCH=${GOTARGET##*-}
    - export GOARCH=${ARCH%%=*}
    - export DEBARCH=${ARCH##*=}
    - export BINARY=gitlab-ci-linter.${GOOS}-${GOARCH}
    - dpkg-buildpackage -us -uc --build=any --target-arch=$DEBARCH
    - mv ../*.${DEBARCH}.deb .
  artifacts:
    name: "${CI_JOB_NAME}"
    paths:
      - "*.deb"
    expire_in: 1 year
  only:
    - tags

debian build linux-i386=386:
  <<: *_build_debian
  dependencies:
    - "release build linux-386"

debian build linux-amd64=amd64:
  <<: *_build_debian
  dependencies:
    - "release build linux-amd64"

debian build linux-arm=arm:
  <<: *_build_debian
  dependencies:
    - "release build linux-arm"

debian build linux-arm64=arm64:
  <<: *_build_debian
  dependencies:
    - "release build linux-arm64"

Update Release note:
  stage: releasenote
  variables:
    VERSION: ${CI_COMMIT_TAG}
  script: ci/update-gitlab-release.sh
  only:
    - tags
